create table if not exists public.wave_clicks (
    id bigint generated by default as identity primary key,
    user_id uuid not null,
    created_at timestamptz not null default now()
);

create index if not exists wave_clicks_user_created_idx
    on public.wave_clicks (user_id, created_at desc);

alter table public.wave_clicks enable row level security;

revoke all on table public.wave_clicks from anon, authenticated;

create or replace function public.register_wave(p_user_id uuid)
returns table (
    accepted boolean,
    total_count bigint,
    retry_after_seconds integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
    v_last_wave timestamptz;
begin
    perform pg_advisory_xact_lock(hashtextextended(p_user_id::text, 0));

    select wc.created_at
      into v_last_wave
      from public.wave_clicks as wc
     where wc.user_id = p_user_id
     order by wc.created_at desc
     limit 1;

    if v_last_wave is not null and v_last_wave > now() - interval '1 hour' then
        return query
        select
            false,
            (select count(*) from public.wave_clicks),
            greatest(
                1,
                ceil(extract(epoch from ((v_last_wave + interval '1 hour') - now())))::integer
            );
        return;
    end if;

    insert into public.wave_clicks (user_id) values (p_user_id);

    return query
    select true, (select count(*) from public.wave_clicks), 0;
end;
$$;

revoke all on function public.register_wave(uuid) from public;
revoke all on function public.register_wave(uuid) from authenticated;
grant execute on function public.register_wave(uuid) to anon;
