create table if not exists public.site_visits (
    id bigint generated by default as identity primary key,
    visited_at timestamptz not null default now(),
    page_path text not null check (char_length(page_path) between 1 and 300),
    page_title text,
    referrer_host text,
    ip_address inet,
    browser text,
    device_type text,
    platform text,
    screen_size text,
    viewport_size text,
    language text,
    timezone text,
    user_agent text
);

create index if not exists site_visits_visited_at_idx
    on public.site_visits (visited_at desc);

create index if not exists site_visits_page_visited_idx
    on public.site_visits (page_path, visited_at desc);

create index if not exists site_visits_ip_visited_idx
    on public.site_visits (ip_address, visited_at desc)
    where ip_address is not null;

alter table public.site_visits enable row level security;

revoke all on table public.site_visits from public, anon, authenticated;
revoke all on sequence public.site_visits_id_seq from public, anon, authenticated;

create or replace function public.register_site_visit(
    p_page_path text,
    p_page_title text,
    p_referrer_host text,
    p_browser text,
    p_device_type text,
    p_platform text,
    p_screen_size text,
    p_viewport_size text,
    p_language text,
    p_timezone text
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_headers jsonb := coalesce(current_setting('request.headers', true), '{}')::jsonb;
    v_ip_address inet;
    v_user_agent text;
    v_page_path text := left(coalesce(nullif(trim(p_page_path), ''), '/'), 300);
    v_recent_ip_requests integer;
begin
    if left(v_page_path, 1) <> '/' then
        v_page_path := left('/' || v_page_path, 300);
    end if;

    begin
        v_ip_address := nullif(trim(split_part(v_headers->>'x-forwarded-for', ',', 1)), '')::inet;
    exception when invalid_text_representation then
        v_ip_address := null;
    end;

    v_user_agent := left(coalesce(v_headers->>'user-agent', 'Unknown'), 500);

    if v_ip_address is not null then
        perform pg_advisory_xact_lock(
            hashtextextended(v_ip_address::text || ':' || v_page_path, 0)
        );

        if exists (
            select 1
              from public.site_visits as sv
             where sv.ip_address = v_ip_address
               and sv.page_path = v_page_path
               and sv.visited_at > now() - interval '30 seconds'
        ) then
            return false;
        end if;

        select count(*)::integer
          into v_recent_ip_requests
          from (
              select 1
                from public.site_visits as sv
               where sv.ip_address = v_ip_address
                 and sv.visited_at > now() - interval '1 minute'
               limit 60
          ) as recent_requests;

        if v_recent_ip_requests >= 60 then
            return false;
        end if;
    end if;

    insert into public.site_visits (
        page_path,
        page_title,
        referrer_host,
        ip_address,
        browser,
        device_type,
        platform,
        screen_size,
        viewport_size,
        language,
        timezone,
        user_agent
    ) values (
        v_page_path,
        left(nullif(trim(p_page_title), ''), 200),
        left(nullif(lower(trim(p_referrer_host)), ''), 253),
        v_ip_address,
        left(coalesce(nullif(trim(p_browser), ''), 'Unknown'), 80),
        left(coalesce(nullif(trim(p_device_type), ''), 'Unknown'), 40),
        left(coalesce(nullif(trim(p_platform), ''), 'Unknown'), 100),
        left(coalesce(nullif(trim(p_screen_size), ''), 'Unknown'), 30),
        left(coalesce(nullif(trim(p_viewport_size), ''), 'Unknown'), 30),
        left(coalesce(nullif(trim(p_language), ''), 'Unknown'), 35),
        left(coalesce(nullif(trim(p_timezone), ''), 'Unknown'), 100),
        v_user_agent
    );

    return true;
end;
$$;

revoke all on function public.register_site_visit(
    text, text, text, text, text, text, text, text, text, text
) from public, anon, authenticated;

grant execute on function public.register_site_visit(
    text, text, text, text, text, text, text, text, text, text
) to anon;

comment on table public.site_visits is
    'Private page-view log for Fiza portfolio traffic. Accessible only through the constrained register_site_visit RPC.';

comment on function public.register_site_visit(
    text, text, text, text, text, text, text, text, text, text
) is
    'Records a rate-limited anonymous portfolio page view without a persistent visitor identifier.';

notify pgrst, 'reload schema';
